### ISSUE TITLE
Feat: Use custom OpenAI compatible API endpoint

### ISSUE THREAD

**Issue by sammcj** [ozgrozer/chatgpt-artifacts#3]
It would be neat if you could easily set a custom OpenAI compatible endpoint to allow the use of tools like Ollama etc...

**Comment by ozgrozer** [comment]
Yeah that's on my todo list

**Comment by ozgrozer** [comment]
Turns out we were already able to use Ollama. I've added a section to readme.

https://github.com/ozgrozer/chatgpt-artifacts#ollama-support

**Comment by sammcj** [comment]
Oh awesome, thanks :D
