### ISSUE TITLE
Does it Support Azure OpenAI? 

### ISSUE THREAD

**Issue by NileshArnaiya** [ozgrozer/chatgpt-artifacts#6]
Hi @ozgrozer 
is it possible to use **Azure OpenAI** service with this? 
Please let me know 👍🏽

**Comment by ozgrozer** [comment]
Yeah added a section to readme

https://github.com/ozgrozer/chatgpt-artifacts#azure-openai-support

**Comment by NileshArnaiya** [comment]
Thanks a lot
